export const emojiData = [
  {
    name: "CONFUSED_SPIRAL",
    slug: "confused_spiral",
    display_name: "Confused spiral",
    path: "/src/assets/emojis/emoji_1.png",
  },
  {
    name: "OK_SIGN_WITH_HEART",
    slug: "ok_sign_with_heart",
    display_name: "OK sign with heart",
    path: "/src/assets/emojis/emoji_2.png",
  },
  {
    name: "BLUSHING_SMILE",
    slug: "blushing_smile",
    display_name: "Blushing smile",
    path: "/src/assets/emojis/emoji_3.png",
  },
  {
    name: "LAUGHING_FACE",
    slug: "laughing_face",
    display_name: "Laughing face",
    path: "/src/assets/emojis/emoji_4.png",
  },
  {
    name: "CALM_CLOSED_EYES",
    slug: "calm_closed_eyes",
    display_name: "Calm closed eyes",
    path: "/src/assets/emojis/emoji_5.png",
  },
  {
    name: "CONTENT_SMILE",
    slug: "content_smile",
    display_name: "Content smile",
    path: "/src/assets/emojis/emoji_6.png",
  },
  {
    name: "HEART_WITH_SWIRL",
    slug: "heart_with_swirl",
    display_name: "Heart with swirl",
    path: "/src/assets/emojis/emoji_7.png",
  },
  {
    name: "HEART_BALLOON",
    slug: "heart_balloon",
    display_name: "Heart balloon",
    path: "/src/assets/emojis/emoji_8.png",
  },
  {
    name: "SPARKLING_EYES",
    slug: "sparkling_eyes",
    display_name: "Sparkling eyes",
    path: "/src/assets/emojis/emoji_9.png",
  },
  {
    name: "PLAYFUL_WINK",
    slug: "playful_wink",
    display_name: "Playful wink",
    path: "/src/assets/emojis/emoji_10.png",
  },
  {
    name: "PEACEFUL_FACE",
    slug: "peaceful_face",
    display_name: "Peaceful face",
    path: "/src/assets/emojis/emoji_11.png",
  },
  {
    name: "SPARKLES",
    slug: "sparkles",
    display_name: "Sparkles",
    path: "/src/assets/emojis/emoji_12.png",
  },
  {
    name: "LAUGHING_WITH_TEARS",
    slug: "laughing_with_tears",
    display_name: "Laughing with tears",
    path: "/src/assets/emojis/emoji_13.png",
  },
  {
    name: "FACE_WITH_BOW",
    slug: "face_with_bow",
    display_name: "Face with bow",
    path: "/src/assets/emojis/emoji_14.png",
  },
  {
    name: "SHY_SMILE",
    slug: "shy_smile",
    display_name: "Shy smile",
    path: "/src/assets/emojis/emoji_15.png",
  },
  {
    name: "LOVING_EYES",
    slug: "loving_eyes",
    display_name: "Loving eyes",
    path: "/src/assets/emojis/emoji_16.png",
  },
  {
    name: "HEART_EYES",
    slug: "heart_eyes",
    display_name: "Heart eyes",
    path: "/src/assets/emojis/emoji_17.png",
  },
  {
    name: "FOUR_LEAF_CLOVER",
    slug: "four_leaf_clover",
    display_name: "Four-leaf clover",
    path: "/src/assets/emojis/emoji_18.png",
  },
  {
    name: "HEART_WITH_SPARKLES",
    slug: "heart_with_sparkles",
    display_name: "Heart with sparkles",
    path: "/src/assets/emojis/emoji_19.png",
  },
  {
    name: "SLEEPY_FACE",
    slug: "sleepy_face",
    display_name: "Sleepy face",
    path: "/src/assets/emojis/emoji_20.png",
  },
  {
    name: "THINKING_FACE",
    slug: "thinking_face",
    display_name: "Thinking face",
    path: "/src/assets/emojis/emoji_21.png",
  },
  {
    name: "NEUTRAL_FACE",
    slug: "neutral_face",
    display_name: "Neutral face",
    path: "/src/assets/emojis/emoji_22.png",
  },
  {
    name: "SURPRISED_FACE",
    slug: "surprised_face",
    display_name: "Surprised face",
    path: "/src/assets/emojis/emoji_23.png",
  },
  {
    name: "EXCLAMATION_QUESTION_MARK",
    slug: "exclamation_question_mark",
    display_name: "Exclamation question mark",
    path: "/src/assets/emojis/emoji_24.png",
  },
  {
    name: "CONFUSED_FACE",
    slug: "confused_face",
    display_name: "Confused face",
    path: "/src/assets/emojis/emoji_25.png",
  },
  {
    name: "SAD_FACE",
    slug: "sad_face",
    display_name: "Sad face",
    path: "/src/assets/emojis/emoji_26.png",
  },
  {
    name: "TIRED_EYES",
    slug: "tired_eyes",
    display_name: "Tired eyes",
    path: "/src/assets/emojis/emoji_27.png",
  },
  {
    name: "SWEAT_DROPS",
    slug: "sweat_drops",
    display_name: "Sweat drops",
    path: "/src/assets/emojis/emoji_28.png",
  },
  {
    name: "CRYING_FACE",
    slug: "crying_face",
    display_name: "Crying face",
    path: "/src/assets/emojis/emoji_29.png",
  },
  {
    name: "PAINED_FACE",
    slug: "pained_face",
    display_name: "Pained face",
    path: "/src/assets/emojis/emoji_30.png",
  },
  {
    name: "SWEAT_SMILE",
    slug: "sweat_smile",
    display_name: "Sweat smile",
    path: "/src/assets/emojis/emoji_31.png",
  },
  {
    name: "TIRED_FACE",
    slug: "tired_face",
    display_name: "Tired face",
    path: "/src/assets/emojis/emoji_32.png",
  },
  {
    name: "EMBARRASSED_FACE",
    slug: "embarrassed_face",
    display_name: "Embarrassed face",
    path: "/src/assets/emojis/emoji_33.png",
  },
  {
    name: "SCARED_FACE",
    slug: "scared_face",
    display_name: "Scared face",
    path: "/src/assets/emojis/emoji_34.png",
  },
  {
    name: "SHY_WITH_BLUSHING",
    slug: "shy_with_blushing",
    display_name: "Shy with blushing",
    path: "/src/assets/emojis/emoji_35.png",
  },
  {
    name: "CRYING_LOUDLY",
    slug: "crying_loudly",
    display_name: "Crying loudly",
    path: "/src/assets/emojis/emoji_36.png",
  },
  {
    name: "NERVOUS_FACE",
    slug: "nervous_face",
    display_name: "Nervous face",
    path: "/src/assets/emojis/emoji_37.png",
  },
  {
    name: "FACE_WITH_SHOCK",
    slug: "face_with_shock",
    display_name: "Face with shock",
    path: "/src/assets/emojis/emoji_38.png",
  },
  {
    name: "ANGRY_FLUSHED_FACE",
    slug: "angry_flushed_face",
    display_name: "Angry flushed face",
    path: "/src/assets/emojis/emoji_39.png",
  },
  {
    name: "SLEEPING_FACE",
    slug: "sleeping_face",
    display_name: "Sleeping face",
    path: "/src/assets/emojis/emoji_40.png",
  },
];
